
export const autoSmeltItems = {
    "minecraft:cod": "minecraft:cooked_cod",
    "minecraft:beef": "minecraft:cooked_beef",
    "minecraft:chicken": "minecraft:cooked_chicken",
    "minecraft:porkchop": "minecraft:cooked_porkchop",
    "minecraft:rabbit": "minecraft:cooked_rabbit",
    "minecraft:mutton": "minecraft:cooked_mutton",
    "minecraft:salmon": "minecraft:cooked_salmon",
    "minecraft:raw_copper": "minecraft:copper_ingot",
    "minecraft:raw_iron": "minecraft:iron_ingot",
    "minecraft:raw_gold": "minecraft:gold_ingot",
    "minecraft:iron_ore": "minecraft:raw_iron",
    "minecraft:gold_ore": "minecraft:raw_gold",
    "minecraft:diamond_ore": "minecraft:diamond",
    "minecraft:emerald_ore": "minecraft:emerald",
    "minecraft:copper_ore": "minecraft:raw_copper",
    "minecraft:quartz_ore": "minecraft:quartz",
    "minecraft:nether_gold_ore": "minecraft:gold_nugget",
    "minecraft:coal_ore": "minecraft:coal",
    "minecraft:lapis_ore": "minecraft:lapis_lazuli",
    "minecraft:redstone_ore": "minecraft:redstone",
    "minecraft:deepslate_coal_ore": "minecraft:coal",
    "minecraft:deepslate_iron_ore": "minecraft:raw_iron",
    "minecraft:deepslate_gold_ore": "minecraft:raw_gold",
    "minecraft:deepslate_diamond_ore": "minecraft:diamond",
    "minecraft:deepslate_lapis_ore": "minecraft:lapis_lazuli",
    "minecraft:deepslate_redstone_ore": "minecraft:redstone",
    "minecraft:deepslate_emerald_ore": "minecraft:emerald",
    "minecraft:deepslate_copper_ore": "minecraft:raw_copper",
    "minecraft:stick": "torch"
}

export const groundBlocks = new Set([
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:podzol",
    "minecraft:mycelium",
    "minecraft:grass_path",
    "minecraft:gravel",
    "minecraft:sandstone",
    "minecraft:red_sandstone",
    "minecraft:stone",
    "minecraft:granite",
    "minecraft:polished_granite",
    "minecraft:diorite",
    "minecraft:polished_diorite",
    "minecraft:andesite",
    "minecraft:polished_andesite",
    "minecraft:sand",
    "minecraft:obsidian",
    "minecraft:blackstone",
    "minecraft:mud",
    "minecraft:packed_mud",
    "minecraft:end_stone",
    "minecraft:netherrack",
    "minecraft:deepslate",
    "minecraft:cobble",
    "minecraft:cobblestone",
    "minecraft:cobbled_deepslate",
    "minecraft:cobbled_deepslate_double_slab",
    "minecraft:mossy_cobblestone",
    "minecraft:farmland",
    "minecraft:clay",
    "minecraft:crimson_nylium",
    "minecraft:warped_nylium",
    "minecraft:crying_obsidian",
    "minecraft:hardened_clay",
    "minecraft:stained_hardened_clay",
    "minecraft:black_glazed_terracotta",
    "minecraft:blue_glazed_terracotta",
    "minecraft:brown_glazed_terracotta",
    "minecraft:cyan_glazed_terracotta",
    "minecraft:gray_glazed_terracotta",
    "minecraft:green_glazed_terracotta",
    "minecraft:light_blue_glazed_terracotta",
    "minecraft:lime_glazed_terracotta",
    "minecraft:magenta_glazed_terracotta",
    "minecraft:orange_glazed_terracotta",
    "minecraft:pink_glazed_terracotta",
    "minecraft:purple_glazed_terracotta",
    "minecraft:red_glazed_terracotta",
    "minecraft:silver_glazed_terracotta",
    "minecraft:white_glazed_terracotta",
    "minecraft:yellow_glazed_terracotta",
    "minecraft:farmland",
    "minecraft:basalt",
    "minecraft:polished_basalt",
    "minecraft:smooth_basalt",
    "minecraft:soul_sand",
    "minecraft:soul_soil",
    "minecraft:nether_brick",
    "minecraft:calcite",
    "minecraft:moss_block",
    "minecraft:mud",
    "minecraft:tuff",
    "minecraft:dripstone_block",
    "minecraft:red_sand",
    "minecraft:gravel",
    "minecraft:suspicious_sand",
    "minecraft:suspicious_gravel",
    "minecraft:packed_mud",
    "minecraft:mud_bricks",
    "minecraft:cracked_deepslate_bricks",
    "minecraft:cracked_deepslate_tiles",
    "minecraft:deepslate_tiles",
    "minecraft:cracked_nether_bricks",
    "minecraft:cracked_polished_blackstone_bricks",
    "minecraft:tuff_bricks",
    "minecraft:deepslate_bricks",
    "minecraft:stonebrick",
    "minecraft:chiseled_tuff_bricks",
    "minecraft:amethyst_block",
]);

export const mobTypes = new Set([
    "minecraft:zombie",
    "minecraft:skeleton",
    "minecraft:spider",
    "minecraft:cave_spider",
    "minecraft:creeper",
    "minecraft:enderman",
    "minecraft:witch",
    "minecraft:husk",
    "minecraft:stray",
    "minecraft:zombified_piglin",
    "minecraft:blaze",
    "minecraft:ghast",
    "minecraft:magma_cube",
    "minecraft:slime",
    "minecraft:phantom",
    "minecraft:drowned",
    "minecraft:guardian",
    "minecraft:elder_guardian",
    "minecraft:shulker",
    "minecraft:ender_dragon",
    "minecraft:wither",
    "minecraft:evoker",
    "minecraft:vindicator",
    "minecraft:vex",
    "minecraft:illager_beast",
    "minecraft:pillager",
    "minecraft:ravager",
    "minecraft:hoglin",
    "minecraft:piglin",
    "minecraft:strider",
    "minecraft:zoglin",
    "minecraft:strider",
    "minecraft:zombie_villager",
    "minecraft:zombie_horse",
    "minecraft:skeleton_horse",
    "minecraft:husk",
    "minecraft:drowned",
    "minecraft:phantom",
    "minecraft:wither_skeleton",
    "minecraft:endermite",
    "minecraft:guardian",
    "minecraft:elder_guardian",
    "minecraft:shulker",
    "minecraft:illusioner",
    "minecraft:zombie_villager_v2",
    "minecraft:evocation_illager",
    "minecraft:vindicator_v2",
    "minecraft:illusioner",
    "minecraft:piglin_brute"
]);

export const animalTypes = new Set([
    "minecraft:cow",
    "minecraft:mooshroom",
    "minecraft:pig",
    "minecraft:sheep",
    "minecraft:chicken",
    "minecraft:horse",
    "minecraft:donkey",
    "minecraft:wolf",
    "minecraft:ocelot",
    "minecraft:parrot",
    "minecraft:rabbit",
    "minecraft:fox",
    "minecraft:polar_bear",
    "minecraft:bee",
    "minecraft:cat",
    "minecraft:cod",
    "minecraft:salmon",
    "minecraft:tropical_fish",
    "minecraft:pufferfish",
    "minecraft:squid",
    "minecraft:bat",
    "minecraft:axolotl",
    "minecraft:glow_squid",
    "minecraft:goat",
    "minecraft:moobloom",
    "minecraft:wandering_trader",
    "minecraft:panda",
    "minecraft:trader_llama",
    "minecraft:llama",
    "minecraft:snowball",
]);

export const conductiveBlocks = new Set([
    "minecraft:iron_block",
    "minecraft:gold_block",
    "minecraft:copper_block",
    "minecraft:netherite_block",
    "minecraft:water",
    "minecraft:iron_bars",
    "minecraft:anvil",
    "minecraft:chipped_anvil",
    "minecraft:damaged_anvil",
    "minecraft:chain",
    "minecraft:hopper",
    "minecraft:dispenser",
    "minecraft:dropper",
    "minecraft:blast_furnace",
    "minecraft:furnace",
    "minecraft:cauldron",
    "minecraft:lightning_rod",
    "minecraft:iron_door",
    "minecraft:iron_trapdoor",
    "minecraft:iron_rail",
    "minecraft:detector_rail",
    "minecraft:activator_rail",
    "minecraft:heavy_weighted_pressure_plate",
    "minecraft:bell"
]);
